version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: phpunit/phpunit
    versions:
    - ">= 8.a, < 9"
  - dependency-name: symfony/mime
    versions:
    - 4.4.10
    - 4.4.19
    - 4.4.20
  - dependency-name: symfony/http-kernel
    versions:
    - 4.3.11
    - 4.4.19
    - 4.4.20
  - dependency-name: mockery/mockery
    versions:
    - 1.3.1
    - 1.3.3
  - dependency-name: symfony/http-foundation
    versions:
    - 4.4.10
    - 4.4.19
  - dependency-name: fzaninotto/faker
    versions:
    - 1.9.1
  - dependency-name: fideloper/proxy
    versions:
    - 4.3.0
